#!/usr/bin/env bash

set -e
set -x
set -o errexit

cd lib

cabal configure --disable-tests

DOCDIR=`mktemp -d -t pages.XXXXXX`

cabal haddock --haddock-option=-o$DOCDIR

HEAD=`git rev-parse HEAD`

cd -

git checkout gh-pages

mv $DOCDIR/* .

git add *.html *.js *.css *.gif *.png
git commit -m "Generated documentation from $HEAD"
git push origin gh-pages
git checkout master

